name: CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest-l
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '11.0.20'
          distribution: 'temurin'

      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build

  release:
    needs: build
    runs-on: ubuntu-latest-l
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Dry run
        uses: goreleaser/goreleaser-action@v6
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          version: latest
          args: release --snapshot

      - name: Release
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
